kisumu/urls.py
from django.urls import path
from . import views

app_name = 'kisumu'

urlpatterns = [
    path('', views.index, name='index'),

    path('contact/', views.contact, name='contact'),

    path('search/', views.search, name='search'),

    path('about/', views.about, name='about'),

    path('causes_list/', views.CauseList.as_view(), name='CauseList'),

    path('<slug:slug>/', views.CauseDetail.as_view(), name='CauseDetail'),

    path('blog_list.html/', views.blog_list, name='blog_list'),

    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.blog_detail, name='blog_detail'),

    path('tag/<slug:tag_slug>/',
         views.blog_detail, name='blog_detail_by_tag'),

]

tkwl/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # app url
    path('', include('kisumu.urls', namespace='kisumu')),

    # pwa urls
    path('', include('pwa.urls')),

    # ckeditor path
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # django Newsletter
    path('newsletter/', include('newsletter.urls')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kisumu/models.py
from django.db import models
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from taggit.managers import TaggableManager
from cloudinary.models import CloudinaryField


# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset() \
            .filter(status='published')


class Cause(models.Model):
    STATUS_CHOICES = (
        ('draft', "Draft"),
        ('publish', "Publish"),
    )

    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100, unique_for_date='publish')
    cause_image = CloudinaryField('CauseImage')
    content = RichTextUploadingField()
    created = models.DateTimeField(auto_now_add=True)
    publish = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                              default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class BlogPost(models.Model):
    STATUS_CHOICES = (
        ('draft', "Draft"),
        ('published', "Published"),
    )

    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100, unique_for_date='publish')
    blog_image = CloudinaryField('BlogImage')
    body = RichTextUploadingField()
    created = models.DateTimeField(auto_now_add=True)
    publish = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                              default='draft')
    tags = TaggableManager()

    objects = models.Manager()  # default manager
    published = PublishedManager()  # custom manager

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('kisumu:blog_detail', args=[self.publish.year,
                                                   self.publish.month,
                                                   self.publish.day,
                                                   self.slug])


class Comment(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=20)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

kisumu/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField

kisumu/views.py
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Cause, BlogPost
from django.core.paginator import *
from .forms import CommentForm
from taggit.models import Tag
from django.contrib.postgres.search import SearchVector
from django.core.mail import send_mail
from itertools import chain


# Create your views here.
def index(request):
    return render(request, 'index.html', {})


def about(request):
    return render(request, 'about.html', {})


class CauseList(ListView):
    queryset = Cause.objects.filter(status='publish').order_by('-publish')
    template_name = 'causes_list.html'
    paginate_by = 4


class CauseDetail(DetailView):
    model = Cause
    template_name = 'causes_detail.html'


def blog_list(request, ):
    posts = BlogPost.published.all()
    p = Paginator(posts, 4)  # paginator object
    # getting the desired page number from url
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page number is not an integer then assign the first page
        page_obj = p.page(1)
    except EmptyPage:
        # if page is empty then return the last page
        page_obj = p.page(p.num_pages)

    context = {'posts': page_obj}
    return render(request,
                  'blog_list.html',
                  context)


def blog_detail(request, year, month, day, post, tag_slug=None):
    post = get_object_or_404(BlogPost,
                             slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # adding Tags in Posts
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post = post.filter(tags__in=[tag])

    # list of active comments
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # comment posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # create a new comment but do not save in the database yet
            new_comment = comment_form.save(commit=False)
            # assign the current post to the comment
            new_comment.post = post
            # save the comment to the database
            new_comment.save()

    else:
        comment_form = CommentForm

    # list of similar functions
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = BlogPost.published.filter(tags__in=post_tags_ids) \
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                        .order_by('-same_tags', '-publish')[:4]

    return render(request,
                  'blog_detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts,
                   'tag': tag,
                   })


def contact(request):
    if request.method == 'POST':
        sender_name = request.POST['sender_name']
        sender_email = request.POST['sender_email']
        message = request.POST['message']

        msg_mail = str(message) + " " + str(sender_email)
        # send an email
        send_mail(sender_name,
                  msg_mail,
                  sender_email,
                  ['odongoanton2@gmail.com'],
                  )

        context = {
            'sender_name': sender_name,
            'sender_email' : sender_email,
            'message': message,
        }

        return render(request, 'contact.html', context)
    else:
        return render(request, 'contact.html', {})


def search(request):
    if request.method == 'GET':
        query = request.GET['search_query']
        search_results = BlogPost.objects.annotate(
            search=SearchVector('title', 'body'),
        ).filter(search=query)

        search_results2 = Cause.objects.annotate(
            search=SearchVector('title', 'content'),
        ).filter(search=query)

        total_results = len(list(chain(search_results, search_results2)))

        context = {'search_results': search_results,
                   'search_results2': search_results2,
                   'total_results': total_results,
                   'query': query}
        return render(request, 'search.html', context)

kisumu/templates/base.html
{% load static %}
{% load kisumu_tags%}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'images/logo.png' %}" type="image/x-icon">
    <link rel="manifest" href="manifest.json">

    <!-- Animate On scroll -->
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

    <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
           integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">

      <!-- font awesome -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome/css/font-awesome.min.css' %}">

      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

      <title>{% block title %} {% endblock %}</title>
  </head>
  <body class="">

    <!-- nav -->
    <nav class="navbar navbar-expand-lg navbar-light bg-success sticky-top">
      <div class="container-fluid">

            <a class="navbar-brand mr-5" href="{% url 'kisumu:index' %}">
                <img src="{% static 'images/logo.png' %}" class="img-fluid">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'kisumu:index' %}">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'kisumu:about' %}">About Us</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'kisumu:CauseList' %}">Causes</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'kisumu:blog_list' %}">Blog</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'kisumu:contact' %}">Contact Us</a>
                    </li>

                </ul>

                <form class="d-flex" method = "GET" action="{% url 'kisumu:search' %}">
                    {% csrf_token %}
                    <input class="form-control mr-2" type="search" placeholder="Search" aria-label="Search"
                           name="search_query">
                    <button class="btn btn-outline-light" type="submit">Search</button>
                </form>

            </div>
      </div>
    </nav>

    <!--nav -->

    <!-- content -->
{% block content %}

{% endblock %}
    <!-- footer -->

<footer class="mt-5 pt-3">
  <div class="container-xxl foot-cont">

    <div class="row">

      <div class="col-md-3" data-aos="fade-up-right" data-aos-duration="1500">
        <img src="{% static 'images/logo.png' %}" class="img-fluid foot-img">
        <p class="mt-2 p-about medium">
          To Kenya With Love (TKWL) is a UK Christian charity that works to significantly transform the lives of children in Kisumu...
        </p>
        <a href=" "><i class="fa fa-facebook fa-2x ml-3"></i></a>
        <a href=" "><i class="fa fa-twitter fa-2x ml-3"></i></a>

      </div>

      <div class="col-md-3" data-aos="zoom-in" data-aos-duration="1500">

        <h3 class="foot-title">Popular Causes</h3>
            {% show_popular_causes 5 %}

      </div>

      <div class="col-md-3" data-aos="zoom-in" data-aos-duration="1500">
          <h3 class="foot-title">Latest Blog Posts</h3>
            {% show_latest_posts 5 %}

      </div>

      <div class="col-md-3" data-aos="fade-up-left" data-aos-duration="1500">
          <h3 class="foot-title"> Reach Out </h3>
          <p class="mt-1 p-about medium">
            <i class="fa fa-phone"> +254 7xxxxxxxx </i>
          </p>

          <p class="mt-1 p-about medium">
            <i class="fa fa-inbox"> tkwlKisumu@gmail.com</i>
          </p>

          <p class="mt-1 p-about medium">
            <i class="fa fa-location-arrow"> Kisumu Office</i>
          </p>

          <form enctype="multipart/form-data"
                action="{% url 'newsletter_subscribe_request' 'To-Kenya-With-Love' %}"
                method="post">
              <h5 class="foot-title">Subscribe to our Monthly Newsletter</h5>
              {% csrf_token %}
              <input class="form-control mr-2" type="email" placeholder="Email Address" aria-label="Email"
                           name="email_field" id="id_email_field" required="">
              <button class="btn btn-success btn-outline-light mt-1 font-weight-bold text-dark" id="id_submit"
                      type="submit" name="submit" value="Subscribe">Subscribe
              </button>

        </form>

      </div>

    </div>

    <div class="row mt-3 ">

      <nav aria-label="breadcrumb container-fluid">
        <ol class="breadcrumb foot-nav">
          <li class="breadcrumb-item">
            <a class=" text-decoration-none text-success font-weight-bold" aria-current="page"
               href="{% url 'kisumu:index' %}">Home</a>
          </li>

          <li class="breadcrumb-item">
            <a class=" text-decoration-none text-success font-weight-bold" href="{% url 'kisumu:about' %}">About Us</a>
          </li>

          <li class="breadcrumb-item">
            <a class=" text-decoration-none text-success font-weight-bold" href="{% url 'kisumu:CauseList' %}">
                Causes</a>
          </li>

          <li class="breadcrumb-item">
            <a class=" text-decoration-none text-success font-weight-bold" href="{% url 'kisumu:blog_list' %}">Blog</a>
          </li>

          <li class="breadcrumb-item">
            <a class=" text-decoration-none text-success font-weight-bold" href="{% url 'kisumu:contact' %}">Contact
                Us</a>
          </li>

        </ol>
      </nav>

    </div>

  </div>
</footer>

    <!-- Optional JavaScript -->
    <!-- Popper.js first, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
      <!-- font awesome -->
    <script src="https://use.fontawesome.com/61bfe38b9a.js"></script>

    <!-- Animate On Scroll -->
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
  </body>
</html>

kisumu/templates/blog_detail.html
{% extends "base.html" %}
{% load static %}
{% load kisumu_tags%}
{% load social_share %}
{% load crispy_forms_tags %}
{%block title%} {{ post.title }} {% endblock %}

{% block content%}

<div class="container-xxl ">

      <div class="row">
        <div class="col-md-8 mt-3">
            <h1 class="text-success text-capitalize font-weight-bold">
              {{ post.title }}
            </h1>
          <p class="text-muted font-italic">Post Tagged as: {{ post.tags.all|join:", " }}</p>
          <p>
           {{ post.body | striptags | linebreaks  }}
          </p>

          <!-- share btns -->

            <h6 class="d-inline-block">{% post_to_facebook object_or_url %}</h6>
            <h6 class="d-inline-block">{% post_to_twitter "New Post: {{post.title }}. Check it out!" object_or_url %}</h6>
            <h6 class="d-inline-block">{% post_to_whatsapp object_or_url "" %}</h6>


          <h4 class="text-capitalize font-weight-bold mt-3 thoughts p-1">
            {% with comments.count as total_comments %}
              {{ total_comments }}  Thought {{ total_comments|pluralize}}
            {% endwith %}
          </h4>

          {% for comment in comments %}
            <div class="comment-cont ml-3 mt-2">
              <p class="text-muted font-italic font-weight-bold">
                Comment {{ forloop.counter }} by {{ comment.name}}/ {{comment.created}}
              </p>
              <p class="comment-body bg-success">
                {{comment.body | linebreaks }}
              </p>
            </div>

            <hr>
          {% endfor %}

          {% if new_comment %}
            <div class="alert alert-success" role="alert">
              Your comment has been submitted successfully but is still awaiting moderation
            </div>
          {% else %}

            <form method="Post" class="comment-form ml-3 p-1">

            <h3 class="font-weight-bold">Leave a Comment</h3>

            {{ comment_form | crispy }}
            {% csrf_token %}

            <button type="submit" class="btn btn-success mt-1">Comment</button>
          </form>
          {% endif %}

        </div>

        <div class="col-md-4">

          <form class="mt-3 mb-3 bg-light p-2" method = "GET" action="{% url 'kisumu:search' %}">
              <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="search_query">
              <button class="btn btn-outline-success mt-2 w-100 p-2 font-weight-bold" type="submit">Search</button>
          </form>

          <div class="similar-posts">

            <h2 class="text-capitalize font-weight-bold mt-3">Simmilar Posts</h2>

            <ul class="list-group list-group-flush">
              {% for post in similar_posts %}
                <li class="list-group-item">
                  <h5>
                    <a href="{{ post.get_absolute_url }}"
                       class="text-decoration-none text-success font-weight-bold">{{post.title }}</a>
                  </h5>
                </li>
              {% empty %}
                <p>There are no similar posts yet</p>
              {% endfor %}

            </ul>

          </div>

          <div class="most-commented-posts">

            <h2 class="text-capitalize font-weight-bold mt-3">Most Commented Posts</h2>

            <ul class="list-group list-group-flush">
              {% get_most_commented_posts as most_commented_posts %}
                {% for post in most_commented_posts %}
                  <li class="list-group-item">
                    <p class="sub-cat"><a href="{{ post.get_absolute_url }}" class="text-decoration-none text-success font-weight-bold">{{ post.title }}</a></p>
                  </li>
                {% endfor %}

            </ul>

          </div>

        </div>
      </div>

    </div>

{% endblock %}

kisumu/templates/causes_detail.html
{% extends "base.html" %}
{% load static %}
{%block title%} Detailed Causes {% endblock %}

{% block content%}

<!-- Causes Body -->

    <div class="container mt-3">
      <h1 class="font-weight-bold text-capitalize">{{ cause.title }}</h1>
      <h6 class="text-muted text-sm font-italic"> {{ cause.publish }}</h6>

      <div class="card " style="width: 100%;">

        <div class="card-body">
          <p class="card-text">
            {{ cause.content | striptags | safe }}
          </p>
        </div>
      </div>
    </div>


      <!-- Donate -->

     <!-- Get In touch for donation -->

       <div class="get-in-touch mt-5">
         <h1 class="p-3 font-weight-bold text-uppercase donate text-center">Are u willing to donate?? <br> Get in touch with us.</h1 >

         <center>
           <a href="{% url 'kisumu:contact' %}"
              class="btn btn-danger btn-lg btn-in-touch font-weight-bold text-center mt-1">GET IN
               TOUCH</a>
         </center>
       </div>

{% endblock %}

kisumu/templates/causes_list.html
{% extends "base.html" %}
{% load static %}
{%block title%} Popular Causes {% endblock %}

{% block content%}

<div class="card causes-header">
      <div class="card-img-overlay">
        <h1 class="card-title font-weight-bold text-light pt-5">Our Causes</h1>
        <p class="card-text text-light"> A kind Gesture can Reach a wound that only compassion can heal</p>
      </div>
    </div>


    <!-- Popular causes -->

      <h1 class="text-center text-success font-weight-bold mt-4">Popular Causes</h1>

      <div class="row justify-content-center container-xxl mt-3">
  {% for cause in cause_list %}
        <div class="col-md-6 col-lg-3 mb-3"
             data-aos="fade-up-right"
             data-aos-duration="1500">
          <div class="card">
            <img src="{{ cause.cause_image.url }}" class="card-img-top causes-img" alt="cause-img">
            <div class="card-body">
              <h4 class="card-title text-capitalize font-weight-bold">
                <a href="{% url 'kisumu:CauseDetail' cause.slug %}" class="text-decoration-none text-danger">
                  {{ cause.title }}</a>
              </h4>
              <p class="card-text">
                {{ cause.content | safe | linebreaks | truncatewords:20 }}
              </p>
              <a href="{% url 'kisumu:CauseDetail' cause.slug %}" class="btn btn-success">READ MORE</a>
            </div>
          </div>
        </div>
  {% endfor %}
    </div>

<!-- pagination -->
      <div class="mx-auto" style="width: 200px;">
    {% if is_paginated %}
        <ul class="pagination pagination-lg">
            <li class="page-item" aria-current="page">
         {% if page_obj.has_previous %}
              <a href="?page={{ page_obj.previous_page_number }}" class="text-decoration-none">
                <span class="page-link bg-success font-weight-bold text-dark">
                  Previous
                </span>
              </a>
         {% endif%}
            </li>
         {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link bg-success font-weight-bold text-dark" href="?page={{ page_obj.next_page_number}}">Next</a>
            </li>
         {% endif%}
          </ul>
    {% endif%}
       </div>

      <!-- Success Stories-->

        <h1 class="text-center font-weight-bold text-success mt-3 mb-3">Success Stories</h1>

        <div id="carouselExampleFade" class="carousel slide carousel-fade success-stories" data-ride="carousel">
          <div class="carousel-inner container-xxl">

            <div class="carousel-item active text-center">
              <img src="{% static 'images/volunter.png' %}" class="img-fluid volunteer-img success-img mt-3 " alt="...">
              <div class="success-info">
                <h2 class="text-success font-weight-bold text-center">Juma Antony</h2>
                <p class="text-light text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              </div>
            </div>

            <div class="carousel-item text-center">
              <img src="{% static 'images/causes.jpg' %}" class="img-fluid volunteer-img success-img mt-3" alt="...">
              <div class="success-info">
                <h2 class="text-success font-weight-bold text-center">Juma Antony</h2>
                <p class="text-light text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              </div>
            </div>

            <div class="carousel-item text-center">
              <img src="{% static 'images/causes1.jpg' %}" class="img-fluid volunteer-img success-img mt-3" alt="...">
              <div class="success-info">
                <h2 class="text-success font-weight-bold text-center">Juma Antony</h2>
                <p class="text-light text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              </div>
            </div>

          </div>
          <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

{% endblock %}

kisumu/templates/contact.html
{% extends "base.html" %}
{% load static %}
{%block title%} Contact Us {% endblock %}

{% block content%}

 <!-- Contact Header -->

    <div class="card bg-dark contact-header">
      <div class="card-img-overlay">
        <h1 class="card-title font-weight-bold text-center text-light pt-5 mt-5">Get In Touch With Us</h1>
      </div>
    </div>

    <div class="container-xxl ">

      <div class="mt-3 text-center">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3989.8137014553936!2d34.78317551420115!3d-0.08718259993638541!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182aa39b35bdeedd%3A0x6f886c58813fb964!2sManyatta%20A%2C%20Kisumu!5e0!3m2!1sen!2ske!4v1600902235819!5m2!1sen!2ske" frameborder="0" style="border:2px solid green;" allowfullscreen="" aria-hidden="false" tabindex="0" class="rounded map"></iframe>
      </div>

          <div class="row mt-3 contact-cont2">

              <div class="col-sm-5">
                  <div class="contct bg-success p-2 rounded height mb-sm-2">
                    <h3 class="conct-title"> <i class="fa fa-address-card-o text-light" aria-hidden="true"></i> Address </h3>
                      <h5>Kisumu, 40100, Kenya</h5><br>
                    <h3 class="conct-title"> <i class="fa fa-phone text-light" aria-hidden="true"></i> Phone</h3>
                      <h5>+254 742 4XXXXXXXX</h5><br>
                    <h3 class="conct-title"> <i class="fa fa-envelope-o text-light" aria-hidden="true"></i> Email</h3>
                      <h5>info@tkwlkisumu.com</h5>
                  </div>
              </div>

              <div class="col-sm-5 ">
                    <form method="post" class=" p-1" action="{% url 'kisumu:contact'%}">
                    {% csrf_token %}
                    <h3 class="font-weight-bold">Get In Touch</h3>

                    <input name="sender_name" type="text" class="form-control mb-2 w-100" id="Name"
                           placeholder="Your Name"
                           required="">

                    <input name = "sender_email" type="email" class="form-control mb-2 w-100" id="Email"
                           aria-describedby="emailHelp"
                           placeholder="Your Email" required="">

                    <textarea name="message" placeholder="Your Message" class="form-control mb-2 w-100" id="Comment"
                              required=""></textarea>

                    <button type="submit" class="btn btn-success">Message</button>
                  </form>

              </div>

          </div>

    </div>


{% endblock %}

kisumu/templates/newsletter/common.html
{% load i18n %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% trans "Newsletter" %}{% endblock title %}</title>
        {% block header %}
        {% endblock header %}
    </head>

    <body>
        {% block body %}
        {% endblock body %}
    </body>
</html>